### ISSUE TITLE
Hi-lights with neovim-vscode 

### ISSUE THREAD

**Issue by raul-bns** [moxer-theme/moxer-code#25]
I'm using moxer with neovim-vscode and I dont have hightlights when I do yanks or when I search the words. It would be possible of include that. Thanks a lot in advance. Your theme it's really nice.

**Comment by equinusocio** [comment]
Hi Raul, we don't support Neovim. This theme is for vscode only.

**Comment by raulbethencourt** [comment]
Ok thanks.
