### ISSUE TITLE
Selection highlight in the list of quick input is lost on VS Code 1.44 

### ISSUE THREAD

**Issue by gnirob** [moxer-theme/moxer-code#5]
**Describe the bug**
Same as the title.

**To Reproduce**
<kbd>⌘</kbd> <kbd>P</kbd> or any way to open quick input widget.

**Expected behavior**
![1-44-default-quick-input](https://user-images.githubusercontent.com/14685751/78853506-98a34d00-7a51-11ea-9cad-7d8e9c624b82.png)

**Screenshots**
![1-44-moxer-quick-input](https://user-images.githubusercontent.com/14685751/78853525-a2c54b80-7a51-11ea-8d65-9f7cb8990e43.png)

**Comment by equinusocio** [comment]
...unfortunately @vscode broken the whole widget by changing all the keys without documenting it. I'm trying to figure out how to set the previous style. But without documentation it's hard.
